const generateLayout = ({ ga_id = "", next_auth }) => {
  return `
import { Inter } from "next/font/google";
import "./globals.css";
${ga_id && `import Script from "next/script"`}
${next_auth && `import NextAuthProvider from "@/app/nextauth/provider"`}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    ${
      ga_id
        ? `
        <>
      <Script
      src={\`https://www.googletagmanager.com/gtag/js?id=\${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}\`}
    />
    <Script id="google-analytics">
        {\`
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '\${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}');
    \`}
      </Script>
    </>
    `
        : ""
    }
      <body className={inter.className}>
      ${
        next_auth
          ? "<NextAuthProvider>{children}</NextAuthProvider>"
          : "{children}"
      }
      </body>
    </html>
      );
}    
`;
};

export default generateLayout;
